### ISSUE TITLE
Status bar missing in ios 8

### ISSUE THREAD

**Issue by dsmo** [zoonooz/ZFDragableModalTransition#21]
In my case, a tab bar and navigation bar based app.
When dismissing a viewcontroller with the ZFDragableModalTransition, the status bar is removed from the `toViewController` which is  the `TabBarController`  during the transition, and will show when the transition is complete.
so you can see the navigationbar grows from 44pt to 64pt immediately.

**Comment by rylinus** [comment]
What i did is just added:
```
[[UIApplication sharedApplication] setStatusBarHidden:NO withAnimation:NO];
```

below
```
[self.modalController dismissViewControllerAnimated:YES completion:nil];
```
in "ZFModalTransitionAnimator.m" to make sure the status bar returns after the transition is complete.
Not sure if it fixes all the time, but it works for me.

**Comment by zoonooz** [comment]
@rylinus @dsmo  What is the view controller structure you have.

**Comment by DanielyBotelho** [comment]
I'm having the same problem, any ideas?

**Comment by zoonooz** [comment]
Hi @DanielyBotelho 

Can you tell me what's vc structure you have. I tried these in demo project
- navigation -> mainVC ---show---> tabbar -> modal
- tabbar -> mainVC ---show---> navigation -> modal

but still cant reproduce. :(

**Comment by burning-git** [comment]
how to use custom view's height?

**Comment by tentenlee100** [comment]
now this issue also  be happen 
vc  structure is tabar -> navigation -> mainvc --- show ---  tabbar -> navigation -> secvc
