### ISSUE TITLE
semi transparent view with solid content

### ISSUE THREAD

**Issue by WendyLei** [zoonooz/ZFDragableModalTransition#23]
I would like to make a semi transparent view of background black (around 75% alpha), and put a webview on top of it, how can I make the content of webview to be solid? I tried to add html body style: rgba(0,0,0,1) for that web view content font color. However not works. The content text still in semi transparent... any idea?

**Comment by zoonooz** [comment]
Hi @WendyLei ,

Have you managed to solve this issue after my reply in email ?
