### ISSUE TITLE
Tip of two new feature =)

### ISSUE THREAD

**Issue by bfernandesbfs** [zoonooz/ZFDragableModalTransition#25]
Transition from top to bottom and close pulling down!...
Transition fade in and fade out!...

=)

**Comment by MikeSilvis** [comment]
@bfernandesbfs I just filed a PR for top to bottom!

https://github.com/zoonooz/ZFDragableModalTransition/pull/28

**Comment by bfernandesbfs** [comment]
Hi !! thanks =) ... @MikeSilvis
