### ISSUE TITLE
uncaught exception 'CALayerInvalidGeometry', 'CALayer position contains NaN: [nan inf]

### ISSUE THREAD

**Issue by WizKIDz** [zoonooz/ZFDragableModalTransition#26]
Not sure if this could be a specific error to my app but I'm getting this full error message

"Terminating app due to uncaught exception 'CALayerInvalidGeometry', reason: 'CALayer position contains NaN: [nan inf]"

I am using the modal transition to a uitableview and adding uitableview to     [self.animator setContentScrollView:detailViewController.tableView];

If there is any clue on how i might be able to change this i could push it as a fix. but if you think its a simple thing to change it would really help my app. I plan to release it soon!

Great job on this wonderful control!

**Comment by zoonooz** [comment]
Hi @WizKIDz ,

I think it should be some value that pass into CGRectMake is not valid. There is someone send email to me about this also, I will look into it.

**Comment by surkis** [comment]
Got same crash,
http://i58.tinypic.com/2mhcth4.png

**Comment by zoonooz** [comment]
Hi @surkis @WizKIDz ,

I cannot reproduce the issue, could you build simple project that simulate your app structure for me. :(

**Comment by zoonooz** [comment]
I just add the code that prevent crash from unexpected value like `Inf` or `Nan`. If you guys still see the crash happen, please re-open the issue.
