### ISSUE TITLE
Update CocoaPods spec 

### ISSUE THREAD

**Issue by hebertialmeida** [zoonooz/ZFDragableModalTransition#27]
Please update CocoaPods spec I'm not able to use @property CGFloat transitionDuration;

**Comment by zoonooz** [comment]
Hi @hebertialmeida ,

I will update the new version in next week after I fix #26 Please use latest file from here in the meantime. 

Sorry

**Comment by hebertialmeida** [comment]
Ok, I'm using from master branch.

`pod 'ZFDragableModalTransition', :head`
