### ISSUE TITLE
Handle iPhone 6 with Xib

### ISSUE THREAD

**Issue by benoitvasseur** [zoonooz/ZFDragableModalTransition#31]
Hello,

First nice work, it's a pretty cool lib.
But I got an issue trying to make it work on iPhone 6. I was using Xib, and the view of the modal controller did not resize correctly (using AutoresizingMask or Auto-Layout). But it was able to make it work with a Storyboard.

I tried the exact same thing by converting your demo project and saw the exact same behavior.

**Comment by benoitvasseur** [comment]
adding

    toViewController.view.frame = [transitionContext containerView].bounds;
before adding `toViewController.view` as subview of `[transitionContext containerView]` seems to fix this.

**Comment by zoonooz** [comment]
Hi @benoitvasseur , thanks for reporting! I tried to add your code but it did not work with iOS7 when showing modal in landscape mode. But it was fixed anyway. :)
