### ISSUE TITLE
ModalViewController does not resize.

### ISSUE THREAD

**Issue by mayankverma** [zoonooz/ZFDragableModalTransition#33]
As seen in the gif, I was the model view controller to cover 75% of screen but the one in demo covers the entire screen. How can I modify that? I have tried setting the frame size but that didnt fix the issue. 

thanks

**Comment by SoXeon** [comment]
I also had this problem, how to change the modalViewController's size, thank you

**Comment by zoonooz** [comment]
Actually the modal in the sample gif is cover 100% of screen which use transparency color as background and has another subview cover part of the screen with white color background.
