### ISSUE TITLE
"bounces" property seems to have no effect.

### ISSUE THREAD

**Issue by ThePantsThief** [zoonooz/ZFDragableModalTransition#34]
Tested on: iOS 8.1

Changing `bounces` to `NO` results in the same presentation animation as if it were set to `YES` (presented from the bottom). Am I missing something or is that property intended for something else?

**Comment by zoonooz** [comment]
Hi @ThePantsThief 

the `bounces` is indicate whether you can drag you modal over the bounds in opposite direction. same behavior as `UIScrollView`

**Comment by ThePantsThief** [comment]
Ahhh. Okay. Can I make a feature request then? I'd like to be able to turn off the bounce when it slides in :)

--
Tanner Bennett
