### ISSUE TITLE
is it compatible with swift?

### ISSUE THREAD

**Issue by EzimetYusup** [zoonooz/ZFDragableModalTransition#35]
I am working on an app with swift , I was trying to use this lib with Objective-C bridge  , and after I present the view controller , whenever I drag to dismiss the viewcontroller it will crash ? what is wrong?  do you have any idea ?
in my case Xcode6.2 , ios 8.2

**Comment by zoonooz** [comment]
Hi @EzimetYusup 

I tried using Swift XCode6.2 and it works. What is the crash message you saw ?

**Comment by EzimetYusup** [comment]
Hi @zoonooz , sorry for delay ,  it only shows (lldb) on log  , I did not use any StoryBoard

**Comment by Jauzee** [comment]
For Swift 1.2:

First: #import "ZFModalTransitionAnimator.h" to yout Bridging header file

Then, in your VC from where you want to open ModalViewController:

var animator: ZFModalTransitionAnimator?

func openDetailView() {
        var storyboard = UIStoryboard(name: "Main", bundle: NSBundle.mainBundle())
        var modalVC: MyViewController = storyboard.instantiateViewControllerWithIdentifier("myViewControllerID") as! MyViewController
        var navController = UINavigationController(rootViewController: MyViewController)
        navController.modalPresentationStyle = .Custom
        navController.navigationBarHidden = true
        
        self.animator = ZFModalTransitionAnimator(modalViewController: navController)
        self.animator!.dragable = true
        self.animator!.bounces = false
        self.animator!.behindViewAlpha = 0.3
        self.animator!.behindViewScale = 1.0
        self.animator!.transitionDuration = 0.5
        self.animator!.direction = ZFModalTransitonDirection.Bottom
        self.animator!.setContentScrollView(modalVC.scrollView)
        navController.transitioningDelegate = self.animator!
        self.presentViewController(navController, animated: true, completion: nil)
    }

**Comment by DeRedBaron** [comment]
@Jauzee Is there any way your code can be used in the prepareForSegue format?

**Comment by forest0xia** [comment]
@EzimetYusup I got the same issue!! Did you solve it?

**Comment by forest0xia** [comment]
@Jauzee  I tried your suggestion, it does not work for me ..

**Comment by zoonooz** [comment]
Hi @forest0xia, can you send me sample project.

**Comment by forest0xia** [comment]
yes no problem. but how can i send it to you?

**Comment by forest0xia** [comment]
@zoonooz ok.. i just sent it to your email..

**Comment by zoonooz** [comment]
@forest0xia you need to declare `animator` as a property because it needs to reference back to the same animator object when dismiss. Sorry that usage instruction is not clear.

**Comment by dimohamdy** [comment]
swift version here
https://github.com/dimohamdy/ZFDragableModalTransitionSwift
