### ISSUE TITLE
Unbalanced calls to begin/end appearance transitions

### ISSUE THREAD

**Issue by grimabe** [zoonooz/ZFDragableModalTransition#49]
Hi,

I am using the latest master branch with the fullsScreen transition implemented.

My view hierarchy is the following : 

UITabBarController -> (the following number represents the tabs)
 1 -> UINavigationController -> UIViewController (we will call it **A**)
 2 -> ...
 3 -> ...
 4 -> ...

Inside the UIViewController **A** I am calling ZFDragableModalTransition with the following code to show another UIViewController **B** as modal
```
        var ctrl = self.storyboard?.instantiateViewControllerWithIdentifier("XXXXXXX") as! XXXXX
        
        ctrl.delegate = self
        ctrl.modalPresentationStyle = .FullScreen
        self.animator = ZFModalTransitionAnimator(modalViewController: ctrl)
        self.animator.dragable = false
        self.animator.bounces = false
        self.animator.direction = ZFModalTransitonDirection.Bottom;
        self.animator.transitionDuration = 0.66
        self.animator.behindViewAlpha = 0.5
        self.animator.behindViewScale = 0.5
        ctrl.transitioningDelegate = self.animator
        
        self.presentViewController(ctrl, animated: true, completion: nil)
```

Once the transition is done I am getting the following notice/warning in the console : 

```
Unbalanced calls to begin/end appearance transitions for <UITabBarController: 0x155d48cd0>.
```

The same message appears when I called the following code inside the **A** UIViewController to dismiss the modal view **B**

```
        self.dismissViewControllerAnimated(true, completion: nil)
```

Any idea where it comes from ?

**Comment by zoonooz** [comment]
Hi @grimabe ,

Seems like `UIModalPresentationFullScreen` already handle appearance method calls. I will just remove that.

**Comment by grimabe** [comment]
It works now, thank you
