### ISSUE TITLE
In-call status bar issue

### ISSUE THREAD

**Issue by ed-mejia** [zoonooz/ZFDragableModalTransition#50]
Hi, 

I'm having an issue when a phone call gets in and you are in the middle of a transition..

1) Run the demo project on simulator
2) Choose bottom modal style
3) Toggle in-call status bar (command + Y )
4) Toggle in-call status bar (command + Y ) - again
5) Close the modal and watch the undesired effect

I'm still trying to find why this happen .

**Comment by zoonooz** [comment]
I think this fix the issue. Not sure this is the same problem. I see the wrong ending stage when dismissing the view controller and the in-call status bar animation happen at the same time.
