### ISSUE TITLE
If you rotate device after presented the second ViewController

### ISSUE THREAD

**Issue by Dendim0n** [zoonooz/ZFDragableModalTransition#51]
It will be black screen after dismiss！
![111](https://cloud.githubusercontent.com/assets/11133087/10094233/d11eed5c-638f-11e5-95cc-3a1d224646ce.gif)

**Comment by Dendim0n** [comment]
If you rotate back the right orientation, it is still no use.
![111](https://cloud.githubusercontent.com/assets/11133087/10094394/01b51bba-6392-11e5-8cab-a1435cffce3d.gif)

**Comment by zoonooz** [comment]
@Dendim0n Thanks for reporting!

I think this issue has been around after I support `UIModalPresentationFullScreen` as I remove the behind view from window's hierarchy but still access the window in `backViewController.view.window.bounds`
