### ISSUE TITLE
Dragging down and releasing modal overrides prefersStatusBarHidden

### ISSUE THREAD

**Issue by irosenb** [zoonooz/ZFDragableModalTransition#58]
When I drag the modal down to dismiss but then change my mind, I let go and it shows the status bar, even though I return `true` for `prefersStatusBarHidden`.

**Comment by felixchan** [comment]
This is the same problem I'm having.

**Comment by irosenb** [comment]
@zoonooz any update on this? Did you figure something out @felixchan

**Comment by zoonooz** [comment]
Sorry.

Apparently I should have called `[transitionContext cancelInteractiveTransition];` when cancelling interaction.

**Comment by irosenb** [comment]
Is the update on cocoa pods?

On Sunday, February 21, 2016, Amornchai Kanokpullwad <
notifications@github.com> wrote:

> Sorry.
>
> Apparently I should have called [transitionContext
> cancelInteractiveTransition]; when cancelling interaction.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/zoonooz/ZFDragableModalTransition/issues/58#issuecomment-186862083>
> .
>


-- 
Isaac Rosenberg
🕓Oneminute | 💻 Founding engineer
🌁 San Francisco, CA
